### PR TITLE
Handle line with both NØ[H] and coordinate

### PR DESCRIPTION
**Pull request by computerlove**
This change handles SOSI-files where a PUNKT-feature's coordinates are specified with 
> NØH x y z
as well as 
> NØH
> x y z

A test case is added, and all tests pass.

### CODE REVIEW

**Comment by computerlove** [comment]
I think the parseData-function needs further work. It assumes that no further features are specified after NØ[H]. 
When «..NØ» is found dict.foundGeom is set to true, and then all following lines are swallowed by 
```javascript
   if (dict.foundGeom) {
       dict.geom.push(line);
  }
```

This my first encounter with SOSI, so I do not know enough to solve this.

**Comment by atlefren** [comment]
Hi!

Nice to see a pull request here!

As you can see, this project has been dormant for a long while, so I do not have the code at the front of my head anymore. From your first comment I assume that this pull request is ready to merge, but after reading your second comment I'm in doubt: does this PR need more work, or is it a general observation that the function needs more work?

I'm happy to merge this PR now, as it seems to me that it improves the library, when it comes to further improvaments I'm in no rush to implement them, but please go ahead and give it a try if you want ;)

**Comment by computerlove** [comment]
Yeah, the PR was ready.
The second comment should perhaps have been a new issue. But I don't have a solution, and I don't know whether the current state will cause any problems. So I guess there is no need to do anything until someone encounters a problem :)

**Comment by atlefren** [comment]
@computerlove I've merged the PR and made a fix that allows LineStrings (Kurve) to have the first coordinate on the same line as NØ[H], see https://github.com/atlefren/sosi.js/commit/822790665e2b36c7ef5860a0799f8c4e62694c58

thanks again!

**Pull request merged**
